name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: f788bb72c14c73af22d668edb4bf4fb0dec92b94b999cdae2dc2ca41dbf6402301-c0b8541b-54f6-4523-8bf7-bea1fa6d3e4900f2431004cd890f
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ""
