name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }} # token automático de GitHub
          action: "upload"
          app_location: "/"        # carpeta raíz donde está tu index.html
          api_location: ""         # vacío si no tienes API
          output_location: ""      # vacío si no usas build
